spring.application.name=auth

server.port=8084

jwt.secret=7hn325CSL9irVF8m2nN4HZOgvGSopeUeNw8G/UhON+A=
jwt.expiration=86400000
gateway.secret=trilhadeaprendizadoapims-gateway
gateway.url=http://localhost:8080